[package]
name = "components"
version = "0.1.0"
authors = ["Kazuya Iimuro <ikazuya0201@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.5.3"
generic-array = "0.13.2"
static_assertions = "1.1.0"

[dependencies.num]
version = "0.2"
default-features = false

[dependencies.heap]
version = "0.1.0"
git = "https://github.com/ikazuya0201/heap"
